In [ ]:
                                                       # NumPy

In [1]:
# It is short for Numerical Python
# NumPy can perform numerical computations at a much faster rate than their Python counterparts and use less memory.

In [153]:
import numpy as np
from numpy.random import rand # Can randomly generate numbers
from numpy.random import randint # Can randomly integers (0, 1, 2) - 0 is lower range, 1 is upper range, 2 is amount

In [3]:
# NumPy can perform mathematical operations on large datasets using its N-dimensional array object, or ndarray

In [4]:
array1 = np.random.randn(2, 3)
print("np.random.randn(x, y) creates an array with random values of dimensions x (rows) by y (columns): \n", array1,
     "\n This object is of type ndarray")

np.random.randn(x, y) creates an array with random values of dimensions x (rows) by y (columns): 
 [[-0.93345443 -0.97700707 -0.18798689]
 [-1.72480337 -0.15284045  0.80287539]] 
 This object is of type ndarray


In [96]:
print("Mathematical operations can be performed on the array. \n"
     "\narray1 + array1: \n", array1 + array1,
     "\n\n array1*5: \n", array1*5)

Mathematical operations can be performed on the array. 

array1 + array1: 
 [[7.95598417 7.91097254 6.30179032]
 [3.81185423 8.51777692 5.3429963 ]] 

 array1*5: 
 [[19.88996043 19.77743135 15.75447579]
 [ 9.52963558 21.2944423  13.35749076]]


In [6]:
array2 = np.array(list(range(5)))
array3 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("Arrays can be created with the np.array function.",
     "\n array2 = np.array(list(range(5))) produces:\n", array2)
print("\nNested lists will produce multi-dimensional arrays.",
     "\n array3 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]) produces: \n", array3)

Arrays can be created with the np.array function. 
 array2 = np.array(list(range(5))) produces:
 [0 1 2 3 4]

Nested lists will produce multi-dimensional arrays. 
 array3 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]) produces: 
 [[1 2 3 4]
 [5 6 7 8]]


In [7]:
arrayZeroes = np.zeros((2, 4))
arrayOnes = np.ones((3, 5))
arrayEmpty = np.empty((2, 3, 4))
print("NumPy gives us the ability to create arrays of certain values.\n",
     "\n arrayZeros = np.zeroes(2, 4) produces:\n", arrayZeroes,
     "\n\n arrayOnes = np.ones(3, 5) produces:\n", arrayOnes,
     "\n\n arrayEmpty = np.empty(2, 3, 4) produces:\n", arrayEmpty)

NumPy gives us the ability to create arrays of certain values.
 
 arrayZeros = np.zeroes(2, 4) produces:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

 arrayOnes = np.ones(3, 5) produces:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

 arrayEmpty = np.empty(2, 3, 4) produces:
 [[[6.23042070e-307 1.86918699e-306 1.69121096e-306 1.78020169e-306]
  [1.37960826e-306 8.45602762e-307 1.11261027e-306 1.11261502e-306]
  [1.42410839e-306 7.56597770e-307 6.23059726e-307 1.42419530e-306]]

 [[7.56602523e-307 1.29061821e-306 9.79110588e-307 8.34424766e-308]
  [1.33508761e-307 1.33511562e-306 8.90103560e-307 1.42410974e-306]
  [1.00132228e-307 1.33511018e-306 1.69119330e-306 8.45610230e-307]]]


In [8]:
array1 = 4 + np.random.randn(2, 3)
print("It is possible to change data types with array1.dtype. The dtype of array1 is:", array1.dtype, "\n",
     array1)
print("\nWe can change this float data type to an int with array1.dtype('int32'):\n", array1.astype('int32'))

It is possible to change data types with array1.dtype. The dtype of array1 is: float64 
 [[3.97799209 3.95548627 3.15089516]
 [1.90592712 4.25888846 2.67149815]]

We can change this float data type to an int with array1.dtype('int32'):
 [[3 3 3]
 [1 4 2]]


In [9]:
print("Arithmetic operations between equal-size arrays such as:\n+ - * /")

Arithmetic operations between equal-size arrays such as:
+ - * /


In [24]:
arr1d = np.arange(10)
print("Indexing on one-dimensional arrays are relatively simple as they act similarly to Python lists.\n",
     "arr1d = np.arrange(10):", arr1d)
arr1d[5:8] = 50
print("\nModifying elements at an index will modify the entire array\n",
     "arr1d[5:8] = 50:", arr1d)
arr1d_slice = arr1d[5:8]
print("\nThey will even be modified if taken out of the array.\n",
     "arr1d_slice = arr1d[5:8]:", arr1d_slice)
arr1d_slice[:] = 100
print("\nUsing [:] will affect all scalars in the array.\n",
     "arr1d_slice[:] = 100:\n",
      "arr1d:", arr1d)

Indexing on one-dimensional arrays are relatively simple as they act similarly to Python lists.
 arr1d = np.arrange(10): [0 1 2 3 4 5 6 7 8 9]

Modifying elements at an index will modify the entire array
 arr1d[5:8] = 50: [ 0  1  2  3  4 50 50 50  8  9]

They will even be modified if taken out of the array.
 arr1d_slice = arr1d[5:8]: [50 50 50]

Using [:] will affect all elements in the array.
 arr1d_slice[:] = 100:
 arr1d: [  0   1   2   3   4 100 100 100   8   9]


In [35]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("We have more indexing options on higher dimensional arrays. The elements at an index are no longer individual scalars "
     "but are one-dimensional arrays, arr2d[2]:", arr2d[2], "."
     "\n\nTo access individual scalars, we must define 2 indices, arr2d[0][2]:", arr2d[0][2], ".")

We have more indexing options on higher dimensional arrays. The elements at an index are no longer individual scalars but are one-dimensional arrays, arr2d[2]: [7 8 9] .

To access individual scalars, we must define 2 indices, arr2d[0][2]: 3 .


In [48]:
print("Considering the above 2-dimensional array. We can slice a few different ways.\n", arr2d,
     "\n\n [:x, y:] will sort all rows up to that xth point and all columns from the yth one until the end.",
     "\nEg. [:2, 1:] will give us up to the 2nd row and the 1st column onwards:\n", arr2d[:2, 1:],
     "\n\nThis is not to be confused with arr2d[:2][1:] which produces a different result:", arr2d[:2][1:])

Considering the above 2-dimensional array. We can slice a few different ways.
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

 [:x, y:] will sort all rows up to that xth point and all columns from the yth one until the end. 
Eg. [:2, 1:] will give us up to the 2nd row and the 1st column onwards:
 [[2 3]
 [5 6]] 

This is not to be confused with arr2d[:2][1:] which produces a different result: [[4 5 6]]


In [87]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print("Boolean indexing can be used to compare 2 different arrays. Supporse we had a list of names and wanted "
     "corresponding values in another column.\n",
     "\nnames:\n", names, "\n", "\ndata:\n", data)
print("\nIf wanted only rows that corresponded to 'Bob', we would write the following: data[names == 'Bob']\n", 
      data[names == 'Bob'])
print("\nFurther indexing can be done, data[names == 'Bob', 2:] produces:\n", data[names == 'Bob', 2:])

Boolean indexing can be used to compare 2 different arrays. Supporse we had a list of names and wanted corresponding values in another column.
 
names:
 ['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe'] 
 
data:
 [[ 0.06738659  0.86237455  0.85396749 -1.48345978]
 [ 1.12964623  0.39990884  0.68696044  1.52373311]
 [-1.04674289  0.83160046  1.4589859  -0.63110633]
 [ 1.52770692  0.74114385  0.03771358  1.96249877]
 [-1.65890588 -0.18166041 -1.16272281 -0.02118995]
 [ 1.89535009 -0.39472929 -0.16359567  0.30725288]
 [ 1.47573639  1.00417534 -0.03352304  0.96663766]]

If wanted only rows that corresponded to 'Bob', we would write the following: data[names == 'Bob']
 [[ 0.06738659  0.86237455  0.85396749 -1.48345978]
 [ 1.52770692  0.74114385  0.03771358  1.96249877]]

Further indexing can be done, data[names == 'Bob', 2:] produces:
 [[ 0.85396749 -1.48345978]
 [ 0.03771358  1.96249877]]


In [94]:
cond1 = names == 'Bob'
print("We can define conditions as variables:\n cond1 = names =='Bob'")
print("\ndata[~cond1]:\n", data[~cond1])
data[data < 0] = 0
print("\nData can also be redifined in this way. data[data < 0] = 0 will replace all negative numbers with 0:\n", data)

We can define conditions as variables:
 cond1 = names =='Bob'

data[~cond1]:
 [[1.12964623 0.39990884 0.68696044 1.52373311]
 [0.         0.83160046 1.4589859  0.        ]
 [0.         0.         0.         0.        ]
 [1.89535009 0.         0.         0.30725288]
 [1.47573639 1.00417534 0.         0.96663766]]

Data can also be redifined in this way. data[data < 0] = 0 will replace all negative numbers with 0:
 [[0.06738659 0.86237455 0.85396749 0.        ]
 [1.12964623 0.39990884 0.68696044 1.52373311]
 [0.         0.83160046 1.4589859  0.        ]
 [1.52770692 0.74114385 0.03771358 1.96249877]
 [0.         0.         0.         0.        ]
 [1.89535009 0.         0.         0.30725288]
 [1.47573639 1.00417534 0.         0.96663766]]


In [181]:
array4 = np.random.randn(5, 4) * 10
print("Our array of random numbers, array4 = np.random.randn(5, 4) is:\n", array4)
print("\nThey are multiple ways to get the mean, sum or std etc.\n", 
      "array4.mean():", array4.mean(), 
      "\nnp.mean(array4)", np.mean(array4))

Our array of random numbers, array4 = np.random.randn(5, 4) is:
 [[-10.93328614  -3.66666856  11.58769945  26.41345713]
 [  3.95651555   9.31825118   9.0818498    1.82237546]
 [  7.32997464 -28.38561913  10.64849598  15.68203515]
 [ -1.46865548   7.06077269  20.98411733  13.56895439]
 [  4.49428538  16.89529355   1.73567272  -4.31390833]]

They are multiple ways to get the mean, sum or std etc.
 array4.mean(): 5.590580638169337 
np.mean(array4) 5.590580638169337


In [182]:
names2 = np.array(['Bob', 'Angela', 'James', 'Jill', 'Ignus'])
print("By using the previous example of an array of values, such as names:\n", names2,
     "\n\nWe can execute these functions with: array4[names2 == 'James'].mean():", array4[names2 == 'James'].mean())
print("\narray4.mean(axis = 0) gives us the averages of all the columns:", array4.mean(axis = 0))
print("array4.mean(axis = 1) gives us the averages of all the rows:", array4.mean(axis = 1))

By using the previous example of an array of values, such as names:
 ['Bob' 'Angela' 'James' 'Jill' 'Ignus'] 

We can execute these functions with: array4[names2 == 'James'].mean(): 1.3187216594626996

array4.mean(axis = 0) gives us the averages of all the columns: [ 0.67576679  0.24440595 10.80756706 10.63458276]
array4.mean(axis = 1) gives us the averages of all the rows: [ 5.85030047  6.044748    1.31872166 10.03629723  4.70283583]
